local addonName, addonTable = ...

addonTable.zoneData = {
[1] = {name = "Dun Morogh"},
[3] = {name = "Badlands"},
[4] = {name = "Blasted Lands"},
[8] = {name = "Swamp of Sorrows"},
[10] = {name = "Duskwood"},
[11] = {name = "Wetlands"},
[12] = {name = "Elwynn Forest"},
[14] = {name = "Durotar"},
[15] = {name = "Dustwallow Marsh"},
[16] = {name = "Azshara"},
[17] = {name = "The Barrens"},
[25] = {name = "Blackrock Mountain"},
[28] = {name = "Western Plaguelands"},
[33] = {name = "Stranglethorn Vale"},
[34] = {name = "Echo Ridge Mine"},
[36] = {name = "Alterac Mountains"},
[38] = {name = "Loch Modan"},
[40] = {name = "Westfall"},
[41] = {name = "Deadwind Pass"},
[44] = {name = "Redridge Mountains"},
[45] = {name = "Arathi Highlands"},
[46] = {name = "Burning Steppes"},
[47] = {name = "The Hinterlands"},
[51] = {name = "Searing Gorge"},
[54] = {name = "Jasperlode Mine"},
[57] = {name = "Fargodeep Mine"},
[85] = {name = "Tirisfal Glades"},
[111] = {name = "Jangolode Mine"},
[113] = {name = "Gold Coast Quarry"},
[130] = {name = "Silverpine Forest"},
[134] = {name = "Gol'Bolar Quarry"},
[135] = {name = "Frostmane Hold"},
[136] = {name = "The Grizzled Den"},
[139] = {name = "Eastern Plaguelands"},
[141] = {name = "Teldrassil"},
[148] = {name = "Darkshore"},
[155] = {name = "Night Web's Hollow"},
[207] = {name = "The Great Sea"},
[209] = {name = "Shadowfang Keep"},
[215] = {name = "Mulgore"},
[257] = {name = "Shadowthread Cave"},
[258] = {name = "Fel Rock"},
[262] = {name = "Ban'ethil Barrow Den"},
[267] = {name = "Hillsbrad Foothills"},
[331] = {name = "Ashenvale"},
[357] = {name = "Feralas"},
[360] = {name = "The Venture Co. Mine"},
[361] = {name = "Felwood"},
[365] = {name = "Burning Blade Coven"},
[371] = {name = "Dustwind Cave"},
[400] = {name = "Thousand Needles"},
[405] = {name = "Desolace"},
[406] = {name = "Stonetalon Mountains"},
[440] = {name = "Tanaris"},
[457] = {name = "The Veiled Sea"},
[490] = {name = "Un'Goro Crater"},
[491] = {name = "Razorfen Kraul"},
[493] = {name = "Moonglade"},
[540] = {name = "The Slithering Scar"},
[618] = {name = "Winterspring"},
[717] = {name = "The Stockade"},
[718] = {name = "Wailing Caverns"},
[719] = {name = "Blackfathom Deeps"},
[721] = {name = "Gnomeregan"},
[722] = {name = "Razorfen Downs"},
[796] = {name = "Scarlet Monastery"},
[800] = {name = "Coldridge Pass"},
[817] = {name = "Skull Rock"},
[818] = {name = "Palemane Rock"},
[981] = {name = "The Gaping Chasm"},
[982] = {name = "The Noxious Lair"},
[1176] = {name = "Zul'Farrak"},
[1337] = {name = "Uldaman"},
[1377] = {name = "Silithus"},
[1397] = {name = "Emerald Forest"},
[1477] = {name = "The Temple of Atal'Hakkar"},
[1497] = {name = "Undercity"},
[1517] = {name = "Uldaman"},
[1519] = {name = "Stormwind City"},
[1537] = {name = "Ironforge"},
[1581] = {name = "The Deadmines"},
[1583] = {name = "Blackrock Spire"},
[1584] = {name = "Blackrock Depths"},
[1637] = {name = "Orgrimmar"},
[1638] = {name = "Thunder Bluff"},
[1657] = {name = "Darnassus"},
[1941] = {name = "Caverns of Time"},
[1977] = {name = "Zul'Gurub"},
[2017] = {name = "Stratholme"},
[2057] = {name = "Scholomance"},
[2100] = {name = "Maraudon"},
[2159] = {name = "Onyxia's Lair"},
[2257] = {name = "Deeprun Tram"},
[2300] = {name = "Caverns of Time"},
[2437] = {name = "Ragefire Chasm"},
[2557] = {name = "Dire Maul"},
[2597] = {name = "Alterac Valley"},
[2677] = {name = "Blackwing Lair"},
[2717] = {name = "Molten Core"},
[3277] = {name = "Warsong Gulch"},
[3358] = {name = "Arathi Basin"},
[3428] = {name = "Ahn'Qiraj"},
[3429] = {name = "Ruins of Ahn'Qiraj"},
[3446] = {name = "Twilight's Run"},
[3456] = {name = "Naxxramas"},
[13649] = {name = "Test Dungeon"},
}
